pipeline:
  identifier: Build_wire_webapp_1689803863290
  name: Build wire-webapp
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1689794626029
        repoName: fredguth/wire-webapp
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest
                  name: npm_test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest1
                  name: npm_test
                  spec:
                    command: npm run lint
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmdist
                  name: npm_dist
                  spec:
                    command: npm run dist
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
